name: .NET Build, Test, and Format

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build, Test, and Format
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Solution
      run: dotnet build --configuration Release --no-restore

    - name: Install dotnet-format
      run: dotnet tool install -g dotnet-format

    - name: Format Code
      run: dotnet-format --fix-style warn --fix-whitespace
      #run: dotnet format --verify-no-changes --verbosity diagnostic
      #run: dotnet-format

    - name: Check for file changes
      id: git-check
      run: |
          git config --global user.name 'Elvin1999'
          git config --global user.email 'camalzade_elvin@mail.ru'
          if [[ $(git status --porcelain) ]]; then
            git add .
            git commit -m "Apply dotnet-format fixes"
            git push
          else
            echo "No changes detected"
      
      
    - name: Run Tests
      run: dotnet test --no-restore --verbosity normal
