name: .NET Build, Test, and Format

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build, Test, and Format
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Solution
      run: dotnet build --configuration Release --no-restore

    - name: Install dotnet-format
      run: dotnet tool install -g dotnet-format

    - name: Format Code
      run: dotnet format <LatestVersionTest> --fix-whitespace --fix-style <warn>
      
    - name: Run Tests
      run: dotnet test --no-restore --verbosity normal
