name: .NET Build, Test, and Format

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build, Test, and Format
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Solution
      run: dotnet build --configuration Release --no-restore

    - name: List Files Before Formatting
      run: |
        find . -name "*.cs" -print0 | xargs -0 cat
        echo "----- End of files before formatting -----"

    - name: Format Code
      run: |
        dotnet tool install -g dotnet-format
        dotnet format --check
        echo "Formatting completed"

    - name: List Files After Formatting (if any)
      run: |
        find . -name "*.cs" -print0 | xargs -0 cat
        echo "----- End of files after formatting (if any) -----"

    - name: Run Tests
      run: dotnet test --no-restore --verbosity normal
